version: "5"
services:
  account-db:
    image: mongo:latest
    container_name: account-db
    ports:
      - "27017:27017"

  account-service:
    image: account-service:latest
    container_name: account-service
    ports:
      - "8080:8080"
    links:
      - account-db

  ticket-db:
    image: mongo:latest
    container_name: ticket-db
    ports:
      - "27018:27017"

  ticket-service:
    image: ticket-service:latest
    container_name: ticket-service
    ports:
      - "8081:8080"
    links:
      - ticket-db
