spring:
  data:
    mongodb:
      database: Account
      uri: mongodb+srv://emirhanusta:bTHXeR8pSg3SGbsp@cluster0.xpmpg3h.mongodb.net
  application:
    name: account-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

server:
  port: 8080
