spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/ticket/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
